# Generated by Django 4.2.7 on 2024-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='type_gift',
            field=models.CharField(max_length=255),
        ),
    ]
