# Generated by Django 5.0.6 on 2024-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="type_gift",
            field=models.CharField(default="non", max_length=255),
        ),
    ]
