# Generated by Django 5.0.6 on 2024-08-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_questionnaire_type_gift"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_type", models.CharField(default="non", max_length=255)),
            ],
        ),
    ]
