# Generated by Django 4.2.7 on 2024-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='text',
            field=models.TextField(),
        ),
    ]
