# Generated by Django 5.0.6 on 2024-08-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_typegift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typegift",
            name="gift_type",
            field=models.CharField(max_length=255),
        ),
    ]
