# Generated by Django 5.0.6 on 2024-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_alter_typegift_gift_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typegift",
            name="gift_type",
        ),
        migrations.AddField(
            model_name="typegift",
            name="gift_type_kg",
            field=models.CharField(default="non", max_length=255),
        ),
        migrations.AddField(
            model_name="typegift",
            name="gift_type_ru",
            field=models.CharField(default="non", max_length=255),
        ),
    ]
