# Generated by Django 4.2.7 on 2024-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_questionnaire_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date_of_birth',
            field=models.CharField(max_length=25, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type_gift',
            field=models.CharField(max_length=255, verbose_name='Type of Gift'),
        ),
        migrations.AlterField(
            model_name='typegift',
            name='gift_type_kg',
            field=models.CharField(default='non', max_length=255, verbose_name='Gift Type (KG)'),
        ),
        migrations.AlterField(
            model_name='typegift',
            name='gift_type_ru',
            field=models.CharField(default='non', max_length=255, verbose_name='Gift Type (RU)'),
        ),
    ]
