# Generated by Django 4.2.7 on 2024-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_questionnaire_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
        migrations.AlterModelOptions(
            name='typegift',
            options={'verbose_name': 'Type of Gift', 'verbose_name_plural': 'Types of Gift'},
        ),
    ]
