# Generated by Django 4.2.7 on 2024-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_alter_questionnaire_options_alter_typegift_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='address',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='apartment_number',
            field=models.TextField(default='', verbose_name='ApartmentNumber'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='district',
            field=models.TextField(default='', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='house_number',
            field=models.TextField(default='', verbose_name='House_Number'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='street',
            field=models.TextField(default='', verbose_name='Street'),
        ),
    ]
