# Generated by Django 4.2.7 on 2024-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_remove_questionnaire_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='district',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='microdistrict',
            field=models.TextField(default='', verbose_name='Micro_District'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='residentail_area',
            field=models.TextField(default='', verbose_name='Residentail_are'),
        ),
    ]
