# Generated by Django 4.2.7 on 2024-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttons',
            name='pkname',
            field=models.CharField(choices=[('Back', 'Back'), ('Connect', 'Connect'), ('AreaInfo', 'AreaInfo'), ('Gift', 'Gift'), ('ChoiceMenu', 'ChoiceMenu'), ('ChoiceLang', 'ChoiceLang'), ('Menu', 'Menu')], default='Back', max_length=255),
        ),
    ]
