# Generated by Django 4.2.7 on 2024-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0003_alter_buttons_pkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttons',
            name='button_kg',
            field=models.CharField(max_length=255, verbose_name='Kyrgyz Button'),
        ),
        migrations.AlterField(
            model_name='buttons',
            name='button_ru',
            field=models.CharField(max_length=255, verbose_name='Russian Button'),
        ),
        migrations.AlterField(
            model_name='buttons',
            name='pkname',
            field=models.CharField(choices=[('Back', 'Back'), ('Connect', 'Connect'), ('AreaInfo', 'AreaInfo'), ('Gift', 'Gift'), ('ChoiceMenu', 'ChoiceMenu'), ('ChoiceLang', 'ChoiceLang'), ('Menu', 'Menu'), ('Yes', 'Yes'), ('No', 'No')], default='Back', max_length=255, verbose_name='Button Type'),
        ),
    ]
