# Generated by Django 4.2.7 on 2024-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0004_alter_buttons_button_kg_alter_buttons_button_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttons',
            options={'verbose_name': 'Button', 'verbose_name_plural': 'Buttons'},
        ),
    ]
