# Generated by Django 4.2.7 on 2024-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0006_alter_buttons_pkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttons',
            name='pkname',
            field=models.CharField(choices=[('Back', 'Back'), ('Connect', 'Connect'), ('AreaInfo', 'AreaInfo'), ('Gift', 'Gift'), ('ChoiceMenu', 'ChoiceMenu'), ('ChoiceLang', 'ChoiceLang'), ('Menu', 'Menu'), ('Yes', 'Yes'), ('No', 'No'), ('GoToMenu', 'GoTuMenu'), ('NoAgain', 'NoAgain')], default='Back', max_length=255, verbose_name='Button Type'),
        ),
    ]
