# Generated by Django 5.0.6 on 2024-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("botwords_ru", models.TextField()),
                ("botwords_kg", models.TextField()),
            ],
        ),
    ]
