# Generated by Django 4.2.7 on 2024-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botwords_ru', models.TextField()),
                ('botwords_kg', models.TextField()),
                ('pkwords', models.CharField(choices=[('Greetings', 'greetings'), ('ChangeLang', 'changelang'), ('InfoOctoberArea', 'infooctoberarea'), ('Mtb', 'mtb'), ('Med', 'med'), ('OOU', 'oou'), ('Connect', 'connect'), ('Links', 'links'), ('Contacts', 'contacts'), ('Choice', 'choice'), ('GoToMenu', 'gotomenu'), ('ChoiceGift', 'choicegift'), ('Questionnaire', 'questionnaire')], default='Greetings', max_length=255)),
            ],
        ),
    ]
