# Generated by Django 4.2.7 on 2024-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botwords',
            name='pkwords',
            field=models.CharField(choices=[('Greetings', 'greetings'), ('ChangeLang', 'changelang'), ('InfoOctoberArea', 'infooctoberarea'), ('Mtb', 'mtb'), ('Med', 'med'), ('OOU', 'oou'), ('Connect', 'connect'), ('Links', 'links'), ('Contacts', 'contacts'), ('Choice', 'choice'), ('GoToMenu', 'gotomenu'), ('ChoiceGift', 'choicegift')], default='Greetings', max_length=255),
        ),
    ]
