# Generated by Django 4.2.7 on 2024-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botwords', '0002_alter_botwords_pkwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botwords',
            name='pkwords',
            field=models.CharField(choices=[('Greetings', 'greetings'), ('ChangeLang', 'changelang'), ('InfoOctoberArea', 'infooctoberarea'), ('Mtb', 'mtb'), ('Med', 'med'), ('OOU', 'oou'), ('Connect', 'connect'), ('Links', 'links'), ('Contacts', 'contacts'), ('Choice', 'choice'), ('GoToMenu', 'gotomenu'), ('ChoiceGift', 'choicegift'), ('Questionnaire', 'questionnaire'), ('StartQuestionnaire', 'startquestionnaire'), ('ChoiceGiftQuestionnaire', 'choicegiftquestionnaire'), ('AnswerName', 'answername'), ('AnswerPhoneNumber', 'answerphonenumber'), ('AnswerDateOfBirth', 'answerdateofbirth'), ('AnswerAdress', 'answeradreass')], default='Greetings', max_length=255),
        ),
    ]
