# Generated by Django 4.2.7 on 2024-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botwords', '0012_alter_botwords_botwords_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botwords',
            options={'verbose_name': 'Bot Word', 'verbose_name_plural': 'Bot Words'},
        ),
    ]
