# Generated by Django 4.2.7 on 2024-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=50)),
                ('kg_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Contats',
        ),
    ]
