# Generated by Django 4.2.7 on 2024-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_contacts_delete_contats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='kg_name',
            field=models.CharField(max_length=50, verbose_name='Kyrgyz Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ru_name',
            field=models.CharField(max_length=50, verbose_name='Russian Name'),
        ),
        migrations.AlterField(
            model_name='links',
            name='kg_name',
            field=models.CharField(max_length=50, verbose_name='Kyrgyz Name'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='links',
            name='ru_name',
            field=models.CharField(max_length=50, verbose_name='Russian Name'),
        ),
    ]
