# Generated by Django 4.2.7 on 2024-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_ru', models.TextField()),
                ('string_kg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_ru', models.TextField()),
                ('string_kg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortNamesMta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_ru', models.TextField()),
                ('string_kg', models.TextField()),
            ],
        ),
    ]
