# Generated by Django 4.2.7 on 2024-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortNamesMta',
        ),
        migrations.AddField(
            model_name='institution',
            name='pkinstitutions',
            field=models.CharField(choices=[('Oou', 'oou'), ('Med', 'med')], default='Oou', max_length=255),
        ),
    ]
