# Generated by Django 5.0.6 on 2024-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string_ru", models.TextField()),
                ("string_kg", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Institutions",
            new_name="MedInstitution",
        ),
    ]
