# Generated by Django 5.0.6 on 2024-08-18 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0002_mta_rename_institutions_medinstitution"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MedInstitution",
            new_name="Institution",
        ),
    ]
