# Generated by Django 4.2.7 on 2024-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_delete_shortnamesmta_institution_pkinstitutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='pkinstitutions',
            field=models.CharField(choices=[('Oou', 'Oou'), ('Med', 'Med')], default='Oou', max_length=255),
        ),
    ]
