# Generated by Django 4.2.7 on 2024-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_institution_pkinstitutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='pkinstitutions',
            field=models.CharField(choices=[('Oou', 'Oou'), ('Med', 'Med')], default='Oou', max_length=255, verbose_name='Institution Type'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='string_kg',
            field=models.TextField(verbose_name='Kyrgyz Text'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='string_ru',
            field=models.TextField(verbose_name='Russian Text'),
        ),
        migrations.AlterField(
            model_name='mta',
            name='string_kg',
            field=models.TextField(verbose_name='Kyrgyz Text'),
        ),
        migrations.AlterField(
            model_name='mta',
            name='string_ru',
            field=models.TextField(verbose_name='Russian Text'),
        ),
    ]
