# Generated by Django 4.2.7 on 2024-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_institution_pkinstitutions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='mta',
            options={'verbose_name': 'MTA', 'verbose_name_plural': 'MTAs'},
        ),
    ]
